# Labeler configuration for automatic PR labeling based on changed files
# Labels will be automatically applied when PRs are opened or updated

# CLI-related changes
cli:
  - changed-files:
      - any-glob-to-any-file: 'src/commands/**'
      - any-glob-to-any-file: 'src/index.ts'

# GitHub API changes
github:
  - changed-files:
      - any-glob-to-any-file: 'src/lib/github.ts'

# AI/OpenAI changes
openai:
  - changed-files:
      - any-glob-to-any-file: 'src/lib/openai.ts'

# Configuration changes
config:
  - changed-files:
      - any-glob-to-any-file: 'tsconfig.json'
      - any-glob-to-any-file: 'eslint.config.js'
      - any-glob-to-any-file: 'commitlint.config.js'
      - any-glob-to-any-file: 'vitest.config.ts'
      - any-glob-to-any-file: 'tsup.config.ts'
      - any-glob-to-any-file: '*.config.js'
      - any-glob-to-any-file: '*.config.mjs'
      - any-glob-to-any-file: '*.config.ts'

# CI/CD and GitHub workflows
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
      - any-glob-to-any-file: '.husky/**'
      - any-glob-to-any-file: 'lint-staged'

# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file: '*.md'
      - any-glob-to-any-file: 'docs/**'
      - any-glob-to-any-file: 'README.md'
      - any-glob-to-any-file: 'CHANGELOG.md'
      - any-glob-to-any-file: 'CONTRIBUTING.md'

# Dependency and package management
dependencies:
  - changed-files:
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'pnpm-lock.yaml'

# Testing changes
tests:
  - changed-files:
      - any-glob-to-any-file: '**/*.spec.ts'
      - any-glob-to-any-file: '**/*.test.ts'
      - any-glob-to-any-file: '**/test/**'
      - any-glob-to-any-file: '**/__tests__/**'
      - any-glob-to-any-file: 'tests/**'
      - any-glob-to-any-file: 'vitest.config.*'

# Build and distribution
build:
  - changed-files:
      - any-glob-to-any-file: 'dist/**'
      - any-glob-to-any-file: 'tsup.config.*'

# Type definitions
types:
  - changed-files:
      - any-glob-to-any-file: 'src/types/**'
      - any-glob-to-any-file: '**/*.d.ts'

# Utility functions
utils:
  - changed-files:
      - any-glob-to-any-file: 'src/utils/**'

# Schemas and validation
schemas:
  - changed-files:
      - any-glob-to-any-file: 'src/schemas/**'

# Labels and templates
labels:
  - changed-files:
      - any-glob-to-any-file: 'src/labels/**'
      - any-glob-to-any-file: 'src/json/**'
      - any-glob-to-any-file: 'src/templates/**'
