name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Manual Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20'
          pnpm-version: '9.12.3'
          install-dependencies: 'true'

      - name: Build project
        run: pnpm build

      - name: Create ZIP archive of dist directory
        run: |
          cd dist
          zip -r ../gh-labels-cli.zip .
          cd ..
          echo "Created gh-labels-cli.zip with the following contents:"
          unzip -l gh-labels-cli.zip

      - name: Disable Husky
        run: |
          npm pkg set scripts.prepare="echo 'Husky disabled in CI'"
          git config --global core.hooksPath /dev/null

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.2.3
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
